name: Deploy to Pterodactyl

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Stáhnout kód z repozitáře
        uses: actions/checkout@v4

      - name: Nahrát soubory přes SFTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT || '16386' }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: '.'  
          remoteDir: '/' 
          dryRun: false
          exclude: 'node_modules/**/*,.git*,.github*'
